import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import { auth, db } from "./firebase-config.js";

/**
 * Logs a student interaction (Query/Answer) to Firestore for future Adaptive Learning training.
 * @param {string} category - Subject or Lab name (e.g., 'Fluid Mechanics', 'Bernoulli Lab')
 * @param {string} studentQuery - The question or query entered by the student
 * @param {string} aiResponse - The response generated by the system/tutor
 */
export async function logStudentInteraction(category, studentQuery, aiResponse) {
    const user = auth.currentUser;

    if (!user) {
        console.warn('Logging skipped: User is not authenticated.');
        return;
    }

    try {
        const interactionData = {
            userId: user.uid,
            userEmail: user.email,
            userName: user.displayName || 'Student',
            category: category,
            studentQuery: studentQuery,
            aiResponse: aiResponse,
            timestamp: serverTimestamp(),
            // Metadata for adaptive learning training
            pageUrl: window.location.href,
            browserTime: new Date().toISOString()
        };

        const docRef = await addDoc(collection(db, "student-interactions"), interactionData);
        console.log(`Interaction logged with ID: ${docRef.id}`);
        return docRef.id;
    } catch (error) {
        console.error('Error logging student interaction:', error);
    }
}

// Function to attach tracker to input fields automatically
export function setupQueryTracker(containerId, category) {
    const container = document.getElementById(containerId);
    if (!container) return;

    // Example interceptor if you have a chat or search box
    const submitBtn = container.querySelector('button[type="submit"]');
    const queryInput = container.querySelector('input, textarea');

    if (submitBtn && queryInput) {
        submitBtn.addEventListener('click', async (e) => {
            const queryText = queryInput.value.trim();
            if (queryText) {
                // Here we assume the system provides a response
                // You can manually log this anywhere in your logic
                await logStudentInteraction(category, queryText, "SYSTEM_RESPONSE_PLACEHOLDER");
            }
        });
    }
}

console.log('Faisal Shameem Interaction Tracker initialized.');
export { db };
